name: CI

on:
  push:
    branches: [main, beta, v1, v2]
  pull_request:
    types: [opened, synchronize, reopened]
env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  NEXT_PUBLIC_STREAMING_HTML_URL: ${{ vars.NEXT_PUBLIC_STREAMING_HTML_URL }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    name: Check quality
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          [
            'ci:attw',
            'ci:eslint',
            'ci:lighthouse',
            'ci:publint',
            'ci:sherif',
            'ci:type',
            'test',
            'test:production',
            'build',
          ]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm-setup-node
      - run: pnpm install --frozen-lockfile
      - if: matrix.command == 'test'
        run: pnpm playwright install
      - run: pnpm ${{ matrix.command }}
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
      - if: matrix.command == 'test'
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
