name: CI

on:
  push:
    branches: [main, beta, next, v1, v2, v3]
  pull_request:
    types: [opened, synchronize, reopened]
env:
  CI: ${{ vars.CI }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  quality:
    name: Check quality
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command: ['ci:test', 'ci:eslint', 'ci:sherif', 'ci:type', 'build']
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/pnpm-setup-node
      - run: pnpm install
      - run: pnpm run ${{ matrix.command }}
      - if: matrix.command == 'ci:test'
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - if: matrix.command == 'build'
        uses: preactjs/compressed-size-action@8518045ed95e94e971b83333085e1cb99aa18aa8 # v2.9.0
        with:
          pattern: 'packages/**/dist/*.{js,cjs,mjs}'
          exclude: '{**/*.map,**/node_modules/**}'
          strip-hash: '-([A-Za-z0-9_-]+)\.'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
