name: CI

on:
  push:
    branches: [main, beta, v1, v2]
  pull_request:
    types: [opened, synchronize, reopened]
env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  CI: ${{ vars.CI }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    name: Check quality
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command: ['ci:attw', 'ci:eslint', 'ci:publint', 'ci:sherif', 'ci:type', 'ci:test', 'ci:bench', 'knip', 'build']
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm-setup-node
      - run: pnpm install --frozen-lockfile
      - if: matrix.command == 'knip'
        run: pnpm prepack
      - if: matrix.command == 'ci:test'
        run: pnpm playwright install
      - run: pnpm ${{ matrix.command }}
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
      - if: matrix.command == 'ci:test'
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - if: matrix.command == 'ci:bench'
        uses: CodSpeedHQ/action@v2
        with:
          run: pnpm ci:bench
          token: ${{ secrets.CODSPEED_TOKEN }}
