name: Compressed Size

on:
  pull_request:
    types: [opened, synchronize, reopened]
env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  CI: ${{ vars.CI }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  size:
    name: Check compressed size
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm-setup-node
      - run: pnpm install --frozen-lockfile

      - name: Report build size
        uses: preactjs/compressed-size-action@v2
        with:
          build-script: 'build'
          pattern: '{packages/**/dist/*.{js,cjs,mjs},websites/visualization/.next/static/chunks/**/*.js,websites/visualization/.next/server/pages/*.{html,json}}'
          exclude: '{**/*.map,**/node_modules/**}'
          strip-hash: "\\w+-(\\w{16}).js$"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
